server.port=0

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=aggregator
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

app.kafka.topics.user-actions=stats.user-actions.v1
app.kafka.topics.events-similarity=stats.events-similarity.v1
