server.port=0
grpc.server.port=0
eureka.instance.metadata-map.grpcPort=${local.grpc.server.port:${grpc.server.port}}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
spring.kafka.consumer.group-id=analyzer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer

app.kafka.topics.user-actions=stats.user-actions.v1
app.kafka.topics.events-similarity=stats.events-similarity.v1

spring.datasource.url=jdbc:postgresql://${RECO_DB_HOST:reco-db}:5432/reco
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${RECO_DB_USER:reco}
spring.datasource.password=${RECO_DB_PASSWORD:reco}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

recommendations.neighbors=10
