server.port=8080

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=main-service
spring.cloud.gateway.routes[0].uri=lb://main-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/admin/**,/users/**,/events/**,/categories/**,/compilations/**
