server.port=0

grpc.client.collector.address=discovery:///collector
grpc.client.collector.enableKeepAlive=true
grpc.client.collector.keepAliveWithoutCalls=true
grpc.client.collector.negotiationType=plaintext

